---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: Restart netfilter-persistent
  ansible.builtin.service:
    name: "{{ netfilter_persistent_service_name }}"
    state: restarted

- name: Reload pf
  ansible.builtin.service:
    name: pf
    state: reloaded

- name: save netfilter rules
  ansible.builtin.command: netfilter-persistent save
  changed_when: true
- name: Save netfilter rules
  ansible.builtin.command: netfilter-persistent save
  changed_when: true
